---
title: "Midterm 3"
author: "Joyce Gill, Khanh Do, Matthew Billings-Chiu"
date: "2025-04-10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(DBI)
library(odbc)
library(RMySQL)
library(tidyverse)
library(dbplyr)
library(RSQLite)
```

## Read Data
```{r}
## Data
data <- read.csv("https://raw.githubusercontent.com/khanhdo05/stats-midterm-3/refs/heads/main/dating_app_behavior_dataset.csv")
data <- data %>% mutate(ID = row_number())
head(data)
```

## Connect to Database
```{r}
mydb <- dbConnect(RSQLite::SQLite(), ":memory:")
```

```{r}
dbExecute(mydb, "CREATE TABLE `app_usage_metrics` (
  `app_usage_time_label` varchar(25) NOT NULL,
  `swipe_time_of_day` varchar(25) NOT NULL,
  'last_active_hour' varchar(3) NOT NULL,
  'ID' int(5)
)")
```

```{r}
## Table 1: App Usage Metrics

app_usage_metrics_data <- data %>%
  dplyr::select(ID, swipe_time_of_day, app_usage_time_label, last_active_hour)

dbWriteTable(conn = mydb, name = 'app_usage_metrics', value = app_usage_metrics_data, append = TRUE, header = FALSE, row.names = FALSE)

dbGetQuery(mydb,"Select * FROM app_usage_metrics LIMIT 5;")
```

```{r}
# Table 2: Does Gender and Sex Correlated to the Number of Likes Received

dbExecute(mydb, "DROP TABLE `gender_related_to_sex`")
dbExecute(mydb, "CREATE TABLE `gender_related_to_sex` (
  `ID` int(11) NOT NULL,
  `gender` varchar(255) NOT NULL,
  `sexual_orientation` varchar(255) NOT NULL,
  `likes_received` int(11) NOT NULL
)")

gender_related_to_sex_data <- data %>%
  dplyr::select(ID, gender, sexual_orientation, likes_received) %>%
  filter(gender != 'Prefer Not to Say') # We are only interested in those we can identify their gender

dbWriteTable(conn = mydb, name = 'gender_related_to_sex', value = gender_related_to_sex_data, append = TRUE, header = FALSE, row.names = FALSE)

dbGetQuery(mydb,"Select * from gender_related_to_sex LIMIT 5;")
```

```{r}
## Table 3: Does the number of likes and how often you swipe correlate to good match results 

## dbExecute(mydb, "DROP TABLE `net_outcome`")
dbExecute(mydb, "CREATE TABLE `net_outcome` (
  `likes_received` int(11) NOT NULL,
  `swipe_right_label` varchar(15) NOT NULL,
  `mutual_matches` int(2) NOT NULL,
  `match_outcome` varchar(30) NOT NULL,
  `ID` int(5) NOT NULL
)")

net_outcome_data <- data %>%
  dplyr::select(likes_received, swipe_right_label, mutual_matches, match_outcome, ID)

dbWriteTable(conn = mydb, name = 'net_outcome', value = net_outcome_data, append = TRUE, header = FALSE, row.names = FALSE)

dbGetQuery(mydb,"Select * from net_outcome LIMIT 5;")
```
